### ISSUE TITLE
SVG images are not displayed correctly on some pages

### ISSUE THREAD

**Issue by 4digitalworld** [gantry/gantry5#3277]
I found that on the default @Joomla `Login page`, if 2-FA is enabled on the website, the SVG login icon for 2-FA is displayed incorrectly in my template on @Gantry 5:

![antry-login1](https://github.com/user-attachments/assets/7cc52280-8884-4620-8fc1-c98b26876eac)

at the same time, in the default `Cassiopeia` Joomla template there is no such problem with displaying this icon:

![gantry-login2](https://github.com/user-attachments/assets/c492b102-571c-4e1d-a2aa-b83c1eda0150)

also SVG icons are displayed incorrectly on the `404 Error page` in my Gantry template:

![gantry-login5](https://github.com/user-attachments/assets/8a3bba52-c692-49bc-a10f-a5c12227ee53)

on all other pages of my Gantry template, SVG icons in the drop-down menu are displayed as expected:

![gantry-login6](https://github.com/user-attachments/assets/e1b1f35e-3a30-47dd-b01b-54c7f7f34a2f)

yes, this is a bug in Gantry with displaying SVG icons on some types of pages, because the default `Cassiopeia` template from Joomla has no problem displaying SVG icons on the same pages.

Joomla 5.2, Gantry 5.5.19

**Comment by N8Solutions** [comment]
Yes, this is a problem. I've usually just corrected it on my own by adding css to the custom.scss file. However, it should be fixed.

**Comment by N8Solutions** [comment]
As an FYI for you @universewrld, and anyone else who finds this. This issue can easily be fixed by adding the following code to your `custom.scss` file. For anyone not familiar with how to do this, you can refer to the [Gantry 5 documentation here](https://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet).

```
.plg_system_webauthn_login_button svg {
  width: 30px;
  margin: 4px;
}
svg {
  vertical-align: middle;
}
```

Tagging @hexplor so he can add this to the next update of Gantry 5.

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by 4digitalworld** [comment]
@gteigland I just updated to Gantry 5.5.20 and this bug still hasn't been fixed. 

Dark theme finally showed up in the Control Panel, cache was cleared.

<img width="316" height="84" alt="Image" src="https://github.com/user-attachments/assets/493d2987-7040-46ad-b7e3-0ed2e6038644" />

**Comment by monikat12titans** [comment]
Hi @universewrld could you please let me know which authentication plugin you are using, as well as the Joomla version?

**Comment by 4digitalworld** [comment]
> Hi [@universewrld](https://github.com/universewrld) could you please let me know which authentication plugin you are using, as well as the Joomla version?

@monikat12titans Joomla `5.3.2`, Gantry `5.5.21`, i'm using the default login page in Joomla.

**Comment by 4digitalworld** [comment]
@monikat12titans the problem with SVG images (404 page) and login is still there in Gantry `5.5.21`, nothing has changed.

**Comment by monikat12titans** [comment]
@universewrld I have verified this on both the Helium and Hydrogen themes with the latest Gantry 5 version (5.5.21), and I did not encounter the SVG icon issue. The CSS appears to be in place. 
Please see the attached screenshot.

<img width="1875" height="901" alt="Image" src="https://github.com/user-attachments/assets/d75cba2b-9fc0-40b9-8de3-d362b85035bf" />

**Comment by 4digitalworld** [comment]
@monikat12titans You attached a screenshot for the `Control Panel` login page, but I mean the login page in the **frontend**.

**Comment by gteigland** [comment]
@universewrld thanks for you clarification. Correct me if I'm wrong but looks like you might be using the Cassiopeia template?
Unfortunately we are not testing RT templates. This community version is specific towards the Gantry framework and the 2 templates Helium and Hydrogen. If you need paid support we can easily handle it tiger12.com/gantry but since this is a frontend login (not backend) tied to a RT theme this is not something we support on this community version.

**Comment by N8Solutions** [comment]
## Here you can see the difference in the size of the SVG and the general CSS applied to the login module is completely off when compared to the way it looks with the Cassiopeia template.

### This is a new installation of Joomla v5.3.2 with Gantry v5.5.21 with Helium v5.5.21. No other extensions have been added to this site.

# 
I've done some testing of my own @gteigland and I can confirm that there is an issue with the way the svg icon is displayed for the login module when using a Gantry template on the **front-end**. The back-end issue with the svg icon was fixed a long time ago but the **front-end** remains problematic.

Here is the link to my test site. Ignore the URL as it is what I used previously for testing the CI builds.
https://j5g5ci.n8solutions.org/

Cassiopeia used as the default template with the `login module` assigned to `sidebar-right`.

<img width="1315" height="596" alt="Image" src="https://github.com/user-attachments/assets/4f1e2fdb-2f0d-460f-8395-a69909ca4c00" />

Below you can see how the `login module` is displayed on the right hand side and compare it to the Cassiopeia template. The styling for the `Sign in with a Passkey` button is completely off which includes the SVG icon.
There is also a smaller aesthetic issue with the `eye` next to the password field. It does not have a border.

<img width="1298" height="768" alt="Image" src="https://github.com/user-attachments/assets/4e6c2595-83d9-4187-8460-8afc16eb1d20" />


I hope this helps clear some things up.

**Comment by gteigland** [comment]
@N8Solutions thanks for the clarification. I understand what you are saying. We will look at this frontend module and and other references. I get what is being asked now. Thanks

**Comment by 4digitalworld** [comment]
> Unfortunately we are not testing RT templates.

@gteigland My website uses the `Kraken` (v1.5.0 / rt_kraken) frontend template from RT, which runs on Gantry 5. 

My screenshot of Cassiopeia was provided to show the difference in how the login button is displayed on the default Joomla template and how this button is displayed on the Gantry template.

You can see this SVG button if you create this frontend menu item on the Joomla website :
<img width="507" height="398" alt="Image" src="https://github.com/user-attachments/assets/e69f9c6c-56e1-4d8e-b0f8-5c58f07eb6ce" />

**Comment by 4digitalworld** [comment]
@gteigland you can also see how the SVG images are not displayed correctly on the `404 error page` in the drop-down menu item on the front-end template that runs on Gantry.

**Comment by gteigland** [comment]
We have replicated this issue and are working on the fix now. Thanks for
your patience.

**Comment by monikat12titans** [comment]
@universewrld This issue has been fixed and included in the latest CI builds. Please download the package from the CI builds section at https://gantry.org/downloads#ci-builds and test it.

**Comment by 4digitalworld** [comment]
> [@universewrld](https://github.com/universewrld) This issue has been fixed and included in the latest CI builds. Please download the package from the CI builds section at https://gantry.org/downloads#ci-builds and test it.


@monikat12titans  I updated to Gantry `5.5.22` and the incorrect display of the SVG **login button** was indeed fixed!

<img width="591" height="372" alt="Image" src="https://github.com/user-attachments/assets/d63e24f9-a089-4819-94ec-5fca85bde8ec" />

but for SVG images in dropdown menu still not fixed incorrect display of SVG for `404 error page` (other pages have no problem displaying these SVG icons):

![gantry-login5](https://github.com/user-attachments/assets/8a3bba52-c692-49bc-a10f-a5c12227ee53)

on all other pages of my Gantry template, SVG icons in the drop-down menu are displayed as expected:

![gantry-login6](https://github.com/user-attachments/assets/e1b1f35e-3a30-47dd-b01b-54c7f7f34a2f)

I added a module with these icons to the menu
