### ISSUE TITLE
Sidebar/mainbody layout incorrect in Hydrogen

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#468]
Testing both left and right sidebar layouts for hydrogen they appear to be incorrect in that the mainbody is assuming the full width of the template instead of being contrained by the block in the grid.

See my example screenshot where mainbody/sidebar is split 80%|20% you will see that the container is set to 75REM wide whereas it should only be 60REM.

Both left and right 2 column presets are incorrect.
![2015-06-15_08-49-27](https://cloud.githubusercontent.com/assets/11683218/8155503/dbcf97c2-133c-11e5-93a7-752f53156cb6.png)

**Comment by kevlardev** [comment]
Were you using the latest version of Gantry when you encountered this (RC3)? This was a problem in RC2 (brought about by the save particles in a layout feature that was added) but was fixed for RC3. Since its been fixed, Ive not been able to reproduce it again.

**Comment by adi8i** [comment]
@w00fz yesterday i was able to reproduce this on Hydrogen RC3, now i can't reproduce it on Hydrogen, same configurations.

In my template, i have Default outline where i can reproduce this bug, but if i duplicate the outline or create a new one and load same preset, will look fine, and i can't repoduce the bug again.

In first case, when it render fine, as you can see in the picture, there's no `g-container` inside `g-main`.
![1](https://cloud.githubusercontent.com/assets/9744973/8177449/8896d2a6-140d-11e5-841a-f6d8d25f227c.png)

![2](https://cloud.githubusercontent.com/assets/9744973/8177450/8d1a0c3a-140d-11e5-9ce9-e11ccce75247.png)

I've tried with your 3 columns layout and this one:
```
preset:
  image: gantry-admin://images/layouts/default.png

layout:
  drawer:
    container:
      - []

  navigation:
    container:
      - particle-menu


  container:
    1:
      - sidebar 20:
        - []
      - main 60:
        - system-messages
        - pagecontent
      - aside 20:
        - []
  ```

**Comment by marktaylor46** [comment]
@kevlardev I have this in Gantry5  RC3 and Hydrogen RC3 .
![2015-06-16_08-42-06](https://cloud.githubusercontent.com/assets/11683218/8178174/f1088456-1403-11e5-84ee-521b9b26b1f0.png)
I tried this in Callisto too and that seems ok - the structure is different.

All I did to reproduce the above is use 2 column (left or right) preset for a single article menu item and added a date particle in sidebar.

**Comment by mahagr** [comment]
I think it might be backwards compatibility issue..?

**Comment by adi8i** [comment]
@w00fz i was able to reproduce it one more time, after you asked me on gitter chat.

1) I've loaded `2 colum right` while `keep particles` was checked and i was able to reproduce the issue.
2) If i load any other layout that have a sidebar, while `keep particle` is checked the issue is still there.
3) I load the preset again, this time without `keep particles` and the issue gone, so now render fine.
4) After this, the issue will not appear again.

**Comment by marktaylor46** [comment]
@adi8i - thanks appreciate the time you put in to replicate the issue that I was seeing - hopefully the guys can correct this now you have given them a reliable method of reproducing the issue.

Cheers, Mark.

**Comment by kevlardev** [comment]
Consolidating these mainbody/sidebar issues to a single issue for a new container approach

**Comment by kevlardev** [comment]
In the meantime, ive added some css to nucleus to reset the width on these erroneous containers to stop the overflow issues from appearing.
