### ISSUE TITLE
Some files in missing in our Bamboo RL builds

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#501]
as mentioned in hipchat, when installing gantry 5 ci build onto one of our template demo/launcher packages (tested with callisto and upcoming template packages) some warnings do show up (although the install itself works), please see pic.

matias narrowed it down to some missing files/directories under /administrator/manifests, namely:
* [x] files/gantry5_nucleus.xml
* [x] files/gantry5_nucleus/install.php
* [x] libraries/gantry5.xml
* [x] packages/pkg_gantry5.xml
* [x] packages/gantry5/install.php

![g5_manifests](https://cloud.githubusercontent.com/assets/5719486/8371910/2ce4c3fe-1bde-11e5-9c40-b9da9a8fb722.jpg)

**Comment by w00fz** [comment]
Ok I fixed the builder and triggered a manual build for the latest template. Please have a look now.

**Comment by kat05** [comment]
just tested the demo package of the latest template and then installed latest gantry 5 ci build. 

the previous warning:
Library Uninstall: Manifest file invalid or not found
is no longer there.

however, the 2 other warnings are still present: 
JInstaller: :Install: Can't find Joomla XML setup file.
JInstaller: :Install: Can't find XML setup file.

![extension manager - install](https://cloud.githubusercontent.com/assets/5719486/8401507/af3a2ed6-1e2f-11e5-840d-ce84be303ba0.jpg)

**Comment by w00fz** [comment]
All the files you mentioned above I added in the builder now, they should be showing in the `administrator/manifests` folder, I am not sure about the other issues tbh.

Something for @mahagr at this point, I guess.

**Comment by mahagr** [comment]
@kat05 Does it only happen on RLs?

**Comment by kat05** [comment]
it happens for example on a brandnew callisto rocketlauncher snapshot. 
it happens there when installing gantry 5 or even roksprocket.

it does NOT happen on a mixxmag rocketlauncher (pre-gantry and maven/jenkins)

**Comment by kat05** [comment]
ok, another brandnew callisto launcher snapshot and i installed the 
/joomla-pkg_gantry5_develop/packages/com_gantry5_vdev-43567c479.zip file 

got the same warnings again:

Warning
JInstaller: :Install: Can't find Joomla XML setup file.
JInstaller: :Install: Can't find XML setup file.

i keep playing

**Comment by kat05** [comment]
/administrator/components/com_gantry5/gantry5.xml
seems missing in a fresh rocketlauncher install

**Comment by kat05** [comment]
language/en-GB/en-GB.files_gantry5_nucleus.sys.ini
seems also missing in a fresh rocketlauncher

**Comment by kat05** [comment]
for roksprocket, these seem missing in a fresh rocketlauncher:

/administrator/components/com_roksprocket/roksprocket.xml
/administrator/components/com_roksprocket/roksprocket_install.script.php
/administrator/manifests/libraries/lib_rokcommon.xml

i guess there are other files missing in the launcher from our other included extensions.

**Comment by w00fz** [comment]
This is more internal than Gantry, related to our Builder for the RLs, I'll look at it but im removing it from the 5.0 release milestone.

**Comment by kat05** [comment]
for pur upcoming template, i used a launcher package and then a 2nd launcher package where i installed gantry 5 again manually.

these files get added when doing the install, so they appear to be missing in the original launcher build:
/administrator/components/com_gantry5/gantry5.xml
/language/en-GB/en-GB.files_gantry5_nucleus.sys.ini
/media/gantry5/engines/nucleus/language/en-GB/en-GB.com_gantry5.ini

**Comment by kat05** [comment]
i've tried rokpad, rokbox, rokbooster, rokajaxsearch too and they did not cause any files to be added. so it seems that it's the components only (i.e gantry 5 and roksprocket) that have files missing in the launcher builds.

**Comment by mahagr** [comment]
@w00fz Where are those file copy operations specified in our build system? Joomla automatically copies manifest files from the package so they aren't defined in xml files.

**Comment by kat05** [comment]
with latest callisto launcher build i am not getting anymore notices when updating gantry itself.

only when updating roksprocket, i get:

Warning
Library Uninstall: Manifest file invalid or not found.

**Comment by kat05** [comment]
i added check marks to those files that are present in latest launcher build.

**Comment by kat05** [comment]
Only file left missing now is:
/language/en-GB/en-GB.files_gantry5_nucleus.ini

But there are no more notices showing up, so the visible issue is now fixed.

**Comment by mahagr** [comment]
I'm going to close this issue; logic for copying the language files should be there, it just cannot be tested.
