### ISSUE TITLE
particle internal iterations of items broken by 5.1.1 update?

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#762]
Please see screenshot of Ethereal rocketlauncher after update to Gantry 5.1.1 - an extra item appears to being added to the iteration in the "blogcontent" particle.
![2015-08-29_17-39-32](https://cloud.githubusercontent.com/assets/11683218/9563245/7fc19fe2-4e75-11e5-824b-32aa3934abb7.png)

**Comment by marktaylor46** [comment]
This is the topic btw....

http://www.rockettheme.com/forum/gantry5-for-joomla/247034-listgriditems-not-processed-right-in-5-1-1?start=0#1230770

**Comment by marktaylor46** [comment]
http://www.rockettheme.com/forum/gantry5-for-joomla/247062-gantry-5-11-problem?start=0#1230951

**Comment by adi8i** [comment]
The issue should be fixed in the latest CI Build, please read: #773

**Comment by kat05** [comment]
for me this issue is now fixed with e5713d1dc for upcoming template an the previous ones too.

**Comment by marktaylor46** [comment]
but it doesn't fix it if you had saved the layout when this bug was present - so @mahagr is still working  on a fix to repair that

**Comment by kat05** [comment]
i had saved layouts in the upcoming template and the ci build still fixed the issue.

**Comment by mahagr** [comment]
Should be fixed now. I mean -- if you saved there are still broken items, but you should be able to delete those.

**Comment by kat05** [comment]
editing g5 particle modules now causes 500 errors.

**Comment by marktaylor46** [comment]
500 fixed now but still an empty particle on front end - despite not being present in admin

**Comment by marktaylor46** [comment]
another member with issues on the map particle:
http://www.rockettheme.com/forum/joomla-template-salient/247095-how-to-remove-map-block?start=0#1231144

**Comment by kat05** [comment]
500 error now gone, but still a double item on frontend (map) but fine in admin.

**Comment by mahagr** [comment]
I'm not being able to reproduce map issue in my local. I took Salient RL and updated it to latest build. Frontend looks just fine to me.

**Comment by kat05** [comment]
i had resaved layouts in ALL outlines before updating to latest ci and then it was still broken for me.
i will retry with a fresh install to be sure.

**Comment by kat05** [comment]
ci 8689a593f seems to fix the broken layout from 5.1.1 for me. :)
